### ISSUE TITLE
Help me - Error npm start - Chapter 2 - two-way-binding

### ISSUE THREAD

**Issue by ijann** [PacktPublishing/Building-Modern-Web-Application-using-Angular#1]
Hello, This sends me an error Chapter 2 
two-way-binding

npm install .... is ok
npm start ... is not ok

Why is this happening?,
use archlinux, node 8.5, use .npm-global in my user
my kernel is 4.9.51

**here I put the terminal error and the log**

------------------------------------------ERROR  terminal------------------------------------------------------------

`
> two-way-binding@1.0.0 prestart /home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding
> npm run build

> two-way-binding@1.0.0 build /home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding
> tsc

> two-way-binding@1.0.0 start /home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding
> concurrently "tsc -w"  "lite-server"

[0] fs.js:1385
[0]     throw error;
[0]     ^
[0] 
[0] Error: watch /home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding ENOSPC
[0]     at _errnoException (util.js:1026:11)
[0]     at FSWatcher.start (fs.js:1383:19)
[0]     at Object.fs.watch (fs.js:1409:11)
[0]     at Object.watchDirectory (/home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding/node_modules/typescript/lib/tsc.js:2377:32)
[0]     at Object.executeCommandLine (/home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding/node_modules/typescript/lib/tsc.js:53355:43)
[0]     at Object.<anonymous> (/home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding/node_modules/typescript/lib/tsc.js:53712:4)
[0]     at Module._compile (module.js:624:30)
[0]     at Object.Module._extensions..js (module.js:635:10)
[0]     at Module.load (module.js:545:32)
[0]     at tryModuleLoad (module.js:508:12)
[0] tsc -w exited with code 1
[1] Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...
[1] ** browser-sync config **
[1] { injectChanges: false,
[1]   files: [ './**/*.{html,htm,css,js}' ],
[1]   watchOptions: { ignored: 'node_modules' },
[1]   server: { baseDir: './', middleware: [ [Function], [Function] ] } }
[1] events.js:182
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: watch . ENOSPC
[1]     at _errnoException (util.js:1026:11)
[1]     at FSWatcher.start (fs.js:1383:19)
[1]     at Object.fs.watch (fs.js:1409:11)
[1]     at createFsWatchInstance (/home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding/node_modules/chokidar/lib/nodefs-handler.js:37:15)
[1]     at setFsWatchListener (/home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding/node_modules/chokidar/lib/nodefs-handler.js:80:15)
[1]     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding/node_modules/chokidar/lib/nodefs-handler.js:228:14)
[1]     at FSWatcher.NodeFsHandler._handleDir (/home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding/node_modules/chokidar/lib/nodefs-handler.js:407:19)
[1]     at FSWatcher.<anonymous> (/home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding/node_modules/chokidar/lib/nodefs-handler.js:455:19)
[1]     at FSWatcher.<anonymous> (/home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding/node_modules/chokidar/lib/nodefs-handler.js:460:16)
[1]     at FSReqWrap.oncomplete (fs.js:154:5)
[1] lite-server exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! two-way-binding@1.0.0 start: `concurrently "tsc -w"  "lite-server"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the two-way-binding@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/users/.npm/_logs/2017-09-26T00_20_57_293Z-debug.log
`

------------------------------------------------------------LOG---------------------------------------------------

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.4.2
3 info using node@v8.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle two-way-binding@1.0.0~prestart: two-way-binding@1.0.0
6 verbose lifecycle two-way-binding@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle two-way-binding@1.0.0~prestart: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
8 verbose lifecycle two-way-binding@1.0.0~prestart: CWD: /home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding
9 silly lifecycle two-way-binding@1.0.0~prestart: Args: [ '-c', 'npm run build' ]
10 silly lifecycle two-way-binding@1.0.0~prestart: Returned: code: 0  signal: null
11 info lifecycle two-way-binding@1.0.0~start: two-way-binding@1.0.0
12 verbose lifecycle two-way-binding@1.0.0~start: unsafe-perm in lifecycle true
13 verbose lifecycle two-way-binding@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
14 verbose lifecycle two-way-binding@1.0.0~start: CWD: /home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding
15 silly lifecycle two-way-binding@1.0.0~start: Args: [ '-c', 'concurrently "tsc -w"  "lite-server"' ]
16 silly lifecycle two-way-binding@1.0.0~start: Returned: code: 1  signal: null
17 info lifecycle two-way-binding@1.0.0~start: Failed to exec start script
18 verbose stack Error: two-way-binding@1.0.0 start: `concurrently "tsc -w"  "lite-server"`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
18 verbose stack     at emitTwo (events.js:125:13)
18 verbose stack     at EventEmitter.emit (events.js:213:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at emitTwo (events.js:125:13)
18 verbose stack     at ChildProcess.emit (events.js:213:7)
18 verbose stack     at maybeClose (internal/child_process.js:927:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
19 verbose pkgid two-way-binding@1.0.0
20 verbose cwd /home/users/Workspace/Angular/Building-Modern-Web-Applications-Using-Angular-master/Chapter02/two-way-binding
21 verbose Linux 4.9.51-1-MANJARO
22 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
23 verbose node v8.5.0
24 verbose npm  v5.4.2
25 error code ELIFECYCLE
26 error errno 1
27 error two-way-binding@1.0.0 start: `concurrently "tsc -w"  "lite-server"`
27 error Exit status 1
28 error Failed at the two-way-binding@1.0.0 start script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]

**Comment by lomelisan** [comment]
Hi @ijann, this worked for me:

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

I hope it helps.
